name: Android Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Android Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Build Android Release
        run: eas build --platform android --profile production --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Wait for build to complete
        run: |
          while true; do
            BUILD_STATUS=$(eas build:list --platform android --status=finished --json | jq -r '.[0].status')
            if [ "$BUILD_STATUS" = "finished" ]; then
              break
            fi
            echo "Waiting for build to complete..."
            sleep 30
          done

      - name: Download build artifacts
        run: |
          EAS_BUILD_ID=$(eas build:list --platform android --status=finished --json | jq -r '.[0].id')
          eas build:download --platform android --id $EAS_BUILD_ID --output=./build.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build.apk
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Android Release Build #${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 