name: Publish Expo Build to GitHub Release

on:
  workflow_dispatch: # 手动触发
  push:
    tags:
      - 'v*' # 当推送 v1.0.0 这样的 Tag 时触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install -g eas-cli && npm install

      - name: Login to Expo
        run: eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # 确保已在 GitHub Secrets 设置

      - name: Build with EAS
        run: eas build --platform android --profile production --non-interactive --no-wait
        env:
          EXPO_NO_CACHE: 1

      - name: Download Build Artifacts
        run: |
          # 等待构建完成并下载文件
          EAS_BUILD_ID=$(eas build:list --platform android --status=finished --json | jq -r '.[0].id')
          eas build:download --platform android --id $EAS_BUILD_ID --output=./build.apk

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build.apk
          tag_name: ${{ github.ref_name }} # 使用触发工作流的 Tag
          body: "Expo Android APK built via EAS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供
